# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /app/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MosleyOpen

# Build rule for target.
MosleyOpen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MosleyOpen
.PHONY : MosleyOpen

# fast build rule for target.
MosleyOpen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/build
.PHONY : MosleyOpen/fast

#=============================================================================
# Target rules for targets named MosleyOpen_autogen_timestamp_deps

# Build rule for target.
MosleyOpen_autogen_timestamp_deps: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MosleyOpen_autogen_timestamp_deps
.PHONY : MosleyOpen_autogen_timestamp_deps

# fast build rule for target.
MosleyOpen_autogen_timestamp_deps/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen_autogen_timestamp_deps.dir/build.make CMakeFiles/MosleyOpen_autogen_timestamp_deps.dir/build
.PHONY : MosleyOpen_autogen_timestamp_deps/fast

#=============================================================================
# Target rules for targets named MosleyOpen_autogen

# Build rule for target.
MosleyOpen_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MosleyOpen_autogen
.PHONY : MosleyOpen_autogen

# fast build rule for target.
MosleyOpen_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen_autogen.dir/build.make CMakeFiles/MosleyOpen_autogen.dir/build
.PHONY : MosleyOpen_autogen/fast

CheckBoxDelegate.o: CheckBoxDelegate.cpp.o
.PHONY : CheckBoxDelegate.o

# target to build an object file
CheckBoxDelegate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CheckBoxDelegate.cpp.o
.PHONY : CheckBoxDelegate.cpp.o

CheckBoxDelegate.i: CheckBoxDelegate.cpp.i
.PHONY : CheckBoxDelegate.i

# target to preprocess a source file
CheckBoxDelegate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CheckBoxDelegate.cpp.i
.PHONY : CheckBoxDelegate.cpp.i

CheckBoxDelegate.s: CheckBoxDelegate.cpp.s
.PHONY : CheckBoxDelegate.s

# target to generate assembly for a file
CheckBoxDelegate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CheckBoxDelegate.cpp.s
.PHONY : CheckBoxDelegate.cpp.s

CoursesDialog.o: CoursesDialog.cpp.o
.PHONY : CoursesDialog.o

# target to build an object file
CoursesDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CoursesDialog.cpp.o
.PHONY : CoursesDialog.cpp.o

CoursesDialog.i: CoursesDialog.cpp.i
.PHONY : CoursesDialog.i

# target to preprocess a source file
CoursesDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CoursesDialog.cpp.i
.PHONY : CoursesDialog.cpp.i

CoursesDialog.s: CoursesDialog.cpp.s
.PHONY : CoursesDialog.s

# target to generate assembly for a file
CoursesDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CoursesDialog.cpp.s
.PHONY : CoursesDialog.cpp.s

CsvExporter.o: CsvExporter.cpp.o
.PHONY : CsvExporter.o

# target to build an object file
CsvExporter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CsvExporter.cpp.o
.PHONY : CsvExporter.cpp.o

CsvExporter.i: CsvExporter.cpp.i
.PHONY : CsvExporter.i

# target to preprocess a source file
CsvExporter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CsvExporter.cpp.i
.PHONY : CsvExporter.cpp.i

CsvExporter.s: CsvExporter.cpp.s
.PHONY : CsvExporter.s

# target to generate assembly for a file
CsvExporter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/CsvExporter.cpp.s
.PHONY : CsvExporter.cpp.s

DailyLeaderboardModel.o: DailyLeaderboardModel.cpp.o
.PHONY : DailyLeaderboardModel.o

# target to build an object file
DailyLeaderboardModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DailyLeaderboardModel.cpp.o
.PHONY : DailyLeaderboardModel.cpp.o

DailyLeaderboardModel.i: DailyLeaderboardModel.cpp.i
.PHONY : DailyLeaderboardModel.i

# target to preprocess a source file
DailyLeaderboardModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DailyLeaderboardModel.cpp.i
.PHONY : DailyLeaderboardModel.cpp.i

DailyLeaderboardModel.s: DailyLeaderboardModel.cpp.s
.PHONY : DailyLeaderboardModel.s

# target to generate assembly for a file
DailyLeaderboardModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DailyLeaderboardModel.cpp.s
.PHONY : DailyLeaderboardModel.cpp.s

DailyLeaderboardWidget.o: DailyLeaderboardWidget.cpp.o
.PHONY : DailyLeaderboardWidget.o

# target to build an object file
DailyLeaderboardWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DailyLeaderboardWidget.cpp.o
.PHONY : DailyLeaderboardWidget.cpp.o

DailyLeaderboardWidget.i: DailyLeaderboardWidget.cpp.i
.PHONY : DailyLeaderboardWidget.i

# target to preprocess a source file
DailyLeaderboardWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DailyLeaderboardWidget.cpp.i
.PHONY : DailyLeaderboardWidget.cpp.i

DailyLeaderboardWidget.s: DailyLeaderboardWidget.cpp.s
.PHONY : DailyLeaderboardWidget.s

# target to generate assembly for a file
DailyLeaderboardWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DailyLeaderboardWidget.cpp.s
.PHONY : DailyLeaderboardWidget.cpp.s

DatabaseManager.o: DatabaseManager.cpp.o
.PHONY : DatabaseManager.o

# target to build an object file
DatabaseManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DatabaseManager.cpp.o
.PHONY : DatabaseManager.cpp.o

DatabaseManager.i: DatabaseManager.cpp.i
.PHONY : DatabaseManager.i

# target to preprocess a source file
DatabaseManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DatabaseManager.cpp.i
.PHONY : DatabaseManager.cpp.i

DatabaseManager.s: DatabaseManager.cpp.s
.PHONY : DatabaseManager.s

# target to generate assembly for a file
DatabaseManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/DatabaseManager.cpp.s
.PHONY : DatabaseManager.cpp.s

HolesTransposedModel.o: HolesTransposedModel.cpp.o
.PHONY : HolesTransposedModel.o

# target to build an object file
HolesTransposedModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/HolesTransposedModel.cpp.o
.PHONY : HolesTransposedModel.cpp.o

HolesTransposedModel.i: HolesTransposedModel.cpp.i
.PHONY : HolesTransposedModel.i

# target to preprocess a source file
HolesTransposedModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/HolesTransposedModel.cpp.i
.PHONY : HolesTransposedModel.cpp.i

HolesTransposedModel.s: HolesTransposedModel.cpp.s
.PHONY : HolesTransposedModel.s

# target to generate assembly for a file
HolesTransposedModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/HolesTransposedModel.cpp.s
.PHONY : HolesTransposedModel.cpp.s

MainWindow.o: MainWindow.cpp.o
.PHONY : MainWindow.o

# target to build an object file
MainWindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/MainWindow.cpp.o
.PHONY : MainWindow.cpp.o

MainWindow.i: MainWindow.cpp.i
.PHONY : MainWindow.i

# target to preprocess a source file
MainWindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/MainWindow.cpp.i
.PHONY : MainWindow.cpp.i

MainWindow.s: MainWindow.cpp.s
.PHONY : MainWindow.s

# target to generate assembly for a file
MainWindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/MainWindow.cpp.s
.PHONY : MainWindow.cpp.s

MosleyOpen_autogen/mocs_compilation.o: MosleyOpen_autogen/mocs_compilation.cpp.o
.PHONY : MosleyOpen_autogen/mocs_compilation.o

# target to build an object file
MosleyOpen_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/MosleyOpen_autogen/mocs_compilation.cpp.o
.PHONY : MosleyOpen_autogen/mocs_compilation.cpp.o

MosleyOpen_autogen/mocs_compilation.i: MosleyOpen_autogen/mocs_compilation.cpp.i
.PHONY : MosleyOpen_autogen/mocs_compilation.i

# target to preprocess a source file
MosleyOpen_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/MosleyOpen_autogen/mocs_compilation.cpp.i
.PHONY : MosleyOpen_autogen/mocs_compilation.cpp.i

MosleyOpen_autogen/mocs_compilation.s: MosleyOpen_autogen/mocs_compilation.cpp.s
.PHONY : MosleyOpen_autogen/mocs_compilation.s

# target to generate assembly for a file
MosleyOpen_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/MosleyOpen_autogen/mocs_compilation.cpp.s
.PHONY : MosleyOpen_autogen/mocs_compilation.cpp.s

PlayerDialog.o: PlayerDialog.cpp.o
.PHONY : PlayerDialog.o

# target to build an object file
PlayerDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/PlayerDialog.cpp.o
.PHONY : PlayerDialog.cpp.o

PlayerDialog.i: PlayerDialog.cpp.i
.PHONY : PlayerDialog.i

# target to preprocess a source file
PlayerDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/PlayerDialog.cpp.i
.PHONY : PlayerDialog.cpp.i

PlayerDialog.s: PlayerDialog.cpp.s
.PHONY : PlayerDialog.s

# target to generate assembly for a file
PlayerDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/PlayerDialog.cpp.s
.PHONY : PlayerDialog.cpp.s

PlayerListWidget.o: PlayerListWidget.cpp.o
.PHONY : PlayerListWidget.o

# target to build an object file
PlayerListWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/PlayerListWidget.cpp.o
.PHONY : PlayerListWidget.cpp.o

PlayerListWidget.i: PlayerListWidget.cpp.i
.PHONY : PlayerListWidget.i

# target to preprocess a source file
PlayerListWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/PlayerListWidget.cpp.i
.PHONY : PlayerListWidget.cpp.i

PlayerListWidget.s: PlayerListWidget.cpp.s
.PHONY : PlayerListWidget.s

# target to generate assembly for a file
PlayerListWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/PlayerListWidget.cpp.s
.PHONY : PlayerListWidget.cpp.s

ScoreEntryDialog.o: ScoreEntryDialog.cpp.o
.PHONY : ScoreEntryDialog.o

# target to build an object file
ScoreEntryDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/ScoreEntryDialog.cpp.o
.PHONY : ScoreEntryDialog.cpp.o

ScoreEntryDialog.i: ScoreEntryDialog.cpp.i
.PHONY : ScoreEntryDialog.i

# target to preprocess a source file
ScoreEntryDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/ScoreEntryDialog.cpp.i
.PHONY : ScoreEntryDialog.cpp.i

ScoreEntryDialog.s: ScoreEntryDialog.cpp.s
.PHONY : ScoreEntryDialog.s

# target to generate assembly for a file
ScoreEntryDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/ScoreEntryDialog.cpp.s
.PHONY : ScoreEntryDialog.cpp.s

ScoreTableModel.o: ScoreTableModel.cpp.o
.PHONY : ScoreTableModel.o

# target to build an object file
ScoreTableModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/ScoreTableModel.cpp.o
.PHONY : ScoreTableModel.cpp.o

ScoreTableModel.i: ScoreTableModel.cpp.i
.PHONY : ScoreTableModel.i

# target to preprocess a source file
ScoreTableModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/ScoreTableModel.cpp.i
.PHONY : ScoreTableModel.cpp.i

ScoreTableModel.s: ScoreTableModel.cpp.s
.PHONY : ScoreTableModel.s

# target to generate assembly for a file
ScoreTableModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/ScoreTableModel.cpp.s
.PHONY : ScoreTableModel.cpp.s

SpinBoxDelegate.o: SpinBoxDelegate.cpp.o
.PHONY : SpinBoxDelegate.o

# target to build an object file
SpinBoxDelegate.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/SpinBoxDelegate.cpp.o
.PHONY : SpinBoxDelegate.cpp.o

SpinBoxDelegate.i: SpinBoxDelegate.cpp.i
.PHONY : SpinBoxDelegate.i

# target to preprocess a source file
SpinBoxDelegate.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/SpinBoxDelegate.cpp.i
.PHONY : SpinBoxDelegate.cpp.i

SpinBoxDelegate.s: SpinBoxDelegate.cpp.s
.PHONY : SpinBoxDelegate.s

# target to generate assembly for a file
SpinBoxDelegate.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/SpinBoxDelegate.cpp.s
.PHONY : SpinBoxDelegate.cpp.s

TeamAssemblyDialog.o: TeamAssemblyDialog.cpp.o
.PHONY : TeamAssemblyDialog.o

# target to build an object file
TeamAssemblyDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamAssemblyDialog.cpp.o
.PHONY : TeamAssemblyDialog.cpp.o

TeamAssemblyDialog.i: TeamAssemblyDialog.cpp.i
.PHONY : TeamAssemblyDialog.i

# target to preprocess a source file
TeamAssemblyDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamAssemblyDialog.cpp.i
.PHONY : TeamAssemblyDialog.cpp.i

TeamAssemblyDialog.s: TeamAssemblyDialog.cpp.s
.PHONY : TeamAssemblyDialog.s

# target to generate assembly for a file
TeamAssemblyDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamAssemblyDialog.cpp.s
.PHONY : TeamAssemblyDialog.cpp.s

TeamLeaderboardModel.o: TeamLeaderboardModel.cpp.o
.PHONY : TeamLeaderboardModel.o

# target to build an object file
TeamLeaderboardModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamLeaderboardModel.cpp.o
.PHONY : TeamLeaderboardModel.cpp.o

TeamLeaderboardModel.i: TeamLeaderboardModel.cpp.i
.PHONY : TeamLeaderboardModel.i

# target to preprocess a source file
TeamLeaderboardModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamLeaderboardModel.cpp.i
.PHONY : TeamLeaderboardModel.cpp.i

TeamLeaderboardModel.s: TeamLeaderboardModel.cpp.s
.PHONY : TeamLeaderboardModel.s

# target to generate assembly for a file
TeamLeaderboardModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamLeaderboardModel.cpp.s
.PHONY : TeamLeaderboardModel.cpp.s

TeamLeaderboardWidget.o: TeamLeaderboardWidget.cpp.o
.PHONY : TeamLeaderboardWidget.o

# target to build an object file
TeamLeaderboardWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamLeaderboardWidget.cpp.o
.PHONY : TeamLeaderboardWidget.cpp.o

TeamLeaderboardWidget.i: TeamLeaderboardWidget.cpp.i
.PHONY : TeamLeaderboardWidget.i

# target to preprocess a source file
TeamLeaderboardWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamLeaderboardWidget.cpp.i
.PHONY : TeamLeaderboardWidget.cpp.i

TeamLeaderboardWidget.s: TeamLeaderboardWidget.cpp.s
.PHONY : TeamLeaderboardWidget.s

# target to generate assembly for a file
TeamLeaderboardWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TeamLeaderboardWidget.cpp.s
.PHONY : TeamLeaderboardWidget.cpp.s

TournamentLeaderboardDialog.o: TournamentLeaderboardDialog.cpp.o
.PHONY : TournamentLeaderboardDialog.o

# target to build an object file
TournamentLeaderboardDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardDialog.cpp.o
.PHONY : TournamentLeaderboardDialog.cpp.o

TournamentLeaderboardDialog.i: TournamentLeaderboardDialog.cpp.i
.PHONY : TournamentLeaderboardDialog.i

# target to preprocess a source file
TournamentLeaderboardDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardDialog.cpp.i
.PHONY : TournamentLeaderboardDialog.cpp.i

TournamentLeaderboardDialog.s: TournamentLeaderboardDialog.cpp.s
.PHONY : TournamentLeaderboardDialog.s

# target to generate assembly for a file
TournamentLeaderboardDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardDialog.cpp.s
.PHONY : TournamentLeaderboardDialog.cpp.s

TournamentLeaderboardModel.o: TournamentLeaderboardModel.cpp.o
.PHONY : TournamentLeaderboardModel.o

# target to build an object file
TournamentLeaderboardModel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardModel.cpp.o
.PHONY : TournamentLeaderboardModel.cpp.o

TournamentLeaderboardModel.i: TournamentLeaderboardModel.cpp.i
.PHONY : TournamentLeaderboardModel.i

# target to preprocess a source file
TournamentLeaderboardModel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardModel.cpp.i
.PHONY : TournamentLeaderboardModel.cpp.i

TournamentLeaderboardModel.s: TournamentLeaderboardModel.cpp.s
.PHONY : TournamentLeaderboardModel.s

# target to generate assembly for a file
TournamentLeaderboardModel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardModel.cpp.s
.PHONY : TournamentLeaderboardModel.cpp.s

TournamentLeaderboardWidget.o: TournamentLeaderboardWidget.cpp.o
.PHONY : TournamentLeaderboardWidget.o

# target to build an object file
TournamentLeaderboardWidget.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardWidget.cpp.o
.PHONY : TournamentLeaderboardWidget.cpp.o

TournamentLeaderboardWidget.i: TournamentLeaderboardWidget.cpp.i
.PHONY : TournamentLeaderboardWidget.i

# target to preprocess a source file
TournamentLeaderboardWidget.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardWidget.cpp.i
.PHONY : TournamentLeaderboardWidget.cpp.i

TournamentLeaderboardWidget.s: TournamentLeaderboardWidget.cpp.s
.PHONY : TournamentLeaderboardWidget.s

# target to generate assembly for a file
TournamentLeaderboardWidget.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/TournamentLeaderboardWidget.cpp.s
.PHONY : TournamentLeaderboardWidget.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MosleyOpen.dir/build.make CMakeFiles/MosleyOpen.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... MosleyOpen_autogen"
	@echo "... MosleyOpen_autogen_timestamp_deps"
	@echo "... MosleyOpen"
	@echo "... CheckBoxDelegate.o"
	@echo "... CheckBoxDelegate.i"
	@echo "... CheckBoxDelegate.s"
	@echo "... CoursesDialog.o"
	@echo "... CoursesDialog.i"
	@echo "... CoursesDialog.s"
	@echo "... CsvExporter.o"
	@echo "... CsvExporter.i"
	@echo "... CsvExporter.s"
	@echo "... DailyLeaderboardModel.o"
	@echo "... DailyLeaderboardModel.i"
	@echo "... DailyLeaderboardModel.s"
	@echo "... DailyLeaderboardWidget.o"
	@echo "... DailyLeaderboardWidget.i"
	@echo "... DailyLeaderboardWidget.s"
	@echo "... DatabaseManager.o"
	@echo "... DatabaseManager.i"
	@echo "... DatabaseManager.s"
	@echo "... HolesTransposedModel.o"
	@echo "... HolesTransposedModel.i"
	@echo "... HolesTransposedModel.s"
	@echo "... MainWindow.o"
	@echo "... MainWindow.i"
	@echo "... MainWindow.s"
	@echo "... MosleyOpen_autogen/mocs_compilation.o"
	@echo "... MosleyOpen_autogen/mocs_compilation.i"
	@echo "... MosleyOpen_autogen/mocs_compilation.s"
	@echo "... PlayerDialog.o"
	@echo "... PlayerDialog.i"
	@echo "... PlayerDialog.s"
	@echo "... PlayerListWidget.o"
	@echo "... PlayerListWidget.i"
	@echo "... PlayerListWidget.s"
	@echo "... ScoreEntryDialog.o"
	@echo "... ScoreEntryDialog.i"
	@echo "... ScoreEntryDialog.s"
	@echo "... ScoreTableModel.o"
	@echo "... ScoreTableModel.i"
	@echo "... ScoreTableModel.s"
	@echo "... SpinBoxDelegate.o"
	@echo "... SpinBoxDelegate.i"
	@echo "... SpinBoxDelegate.s"
	@echo "... TeamAssemblyDialog.o"
	@echo "... TeamAssemblyDialog.i"
	@echo "... TeamAssemblyDialog.s"
	@echo "... TeamLeaderboardModel.o"
	@echo "... TeamLeaderboardModel.i"
	@echo "... TeamLeaderboardModel.s"
	@echo "... TeamLeaderboardWidget.o"
	@echo "... TeamLeaderboardWidget.i"
	@echo "... TeamLeaderboardWidget.s"
	@echo "... TournamentLeaderboardDialog.o"
	@echo "... TournamentLeaderboardDialog.i"
	@echo "... TournamentLeaderboardDialog.s"
	@echo "... TournamentLeaderboardModel.o"
	@echo "... TournamentLeaderboardModel.i"
	@echo "... TournamentLeaderboardModel.s"
	@echo "... TournamentLeaderboardWidget.o"
	@echo "... TournamentLeaderboardWidget.i"
	@echo "... TournamentLeaderboardWidget.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
